In [1]:
import pandas as pd

# Load the datasets
no_sp_df = pd.read_csv('../log/tmplog_finalTest4.csv')
sp_df = pd.read_csv('../log/tmplog_finalTest4_SP.csv')

# Display the first few rows of each DataFrame to understand the structure
no_sp_df.head(), sp_df.head()

(                       flow id:  first send:  last send:  last arrive:  \
 0  11:0:11 11:0:41 10099 100 17     2.015403   83.183409     83.290538
 1  11:0:11 11:0:41 10097 100 17     2.014783  103.064268    103.065191
 2  11:0:11 11:0:41 10096 100 17     2.014472   84.624791     84.648335
 3  11:0:11 11:0:41 10093 100 17     2.013636   84.337275     84.387197
 4  11:0:11 11:0:41 10092 100 17     2.013325   83.174090     83.281219

    send num:  receive num:  send size:  receive size:        FCT:  origin_pg:  \
 0      31215         31296     1050000        1050000   81.275135           3
 1      32520         32597     1049369        1049369  101.050407           3
 2      33502         33584     1049895        1049895   82.633863           3
 3      32829         32911     1049740        1049740   82.373561           3
 4      31208         31289     1050000        1050000   81.267895           3

    transfer delay:
 0                0
 1                0
 2                0
 3                0
 4                0  ,
                        flow id:  first send:  last send:   last arrive:  \
 0  11:0:11 11:0:41 10099 100 17     2.015403   82.924488   83.024381381
 1  11:0:11 11:0:41 10097 100 17     2.014783  103.419502  103.420126872
 2  11:0:11 11:0:41 10096 100 17     2.014472   84.667584   84.691622675
 3  11:0:11 11:0:41 10093 100 17     2.013636   84.381762    84.42441131
 4  11:0:11 11:0:41 10092 100 17     2.013325   83.402574   83.487896235

    send num:  receive num:  send size:  receive size:        FCT:  origin_pg:  \
 0      31267         31348     1050000        1050000   81.008978           3
 1      32899         32975     1049369        1049369  101.405344           3
 2      33792         33874     1049895        1049895   82.677151           3
 3      33115         33197     1049740        1049740   82.410775           3
 4      31650         31731     1050000        1050000   81.474572           3

    transfer delay:
 0                0
 1                0
 2                0
 3                0
 4                0  )

In [2]:
# Merge the datasets on 'flow id:' column
merged_df = pd.merge(no_sp_df, sp_df, on='flow id:', suffixes=('_no_sp', '_sp'))

# Calculate FCT change and percentage change
merged_df['FCT Change'] = merged_df['FCT:_sp'] - merged_df['FCT:_no_sp']
merged_df['FCT % Change'] = (merged_df['FCT Change'] / merged_df['FCT:_no_sp']) * 100

# Display the new dataframe with changes
merged_df[['flow id:', 'FCT:_no_sp', 'FCT:_sp', 'FCT Change', 'FCT % Change']].head()

,flow id:,FCT:_no_sp,FCT:_sp,FCT Change,FCT % Change
0,11:0:11 11:0:41 10099 100 17,81.275135,81.008978,-0.266157,-0.327477
1,11:0:11 11:0:41 10097 100 17,101.050407,101.405344,0.354936,0.351247
2,11:0:11 11:0:41 10096 100 17,82.633863,82.677151,0.043288,0.052385
3,11:0:11 11:0:41 10093 100 17,82.373561,82.410775,0.037215,0.045178
4,11:0:11 11:0:41 10092 100 17,81.267895,81.474572,0.206677,0.254315

In [3]:
# merged_df = pd.read_csv('./result_multiCast_BestWithOneChannelAllowed.csv')
# merged_df = pd.read_csv('./result_4.csv')
merged_df

,flow id:,first send:_no_sp,last send:_no_sp,last arrive:_no_sp,send num:_no_sp,receive num:_no_sp,send size:_no_sp,receive size:_no_sp,FCT:_no_sp,origin_pg:_no_sp,...,last arrive:_sp,send num:_sp,receive num:_sp,send size:_sp,receive size:_sp,FCT:_sp,origin_pg:_sp,transfer delay:_sp,FCT Change,FCT % Change
0,11:0:11 11:0:41 10099 100 17,2.015403,83.183409,83.290538,31215,31296,1050000,1050000,81.275135,3,...,83.024381381,31267,31348,1050000,1050000,81.008978,3,0,-0.266157,-0.327477
1,11:0:11 11:0:41 10097 100 17,2.014783,103.064268,103.065191,32520,32597,1049369,1049369,101.050407,3,...,103.420126872,32899,32975,1049369,1049369,101.405344,3,0,0.354936,0.351247
2,11:0:11 11:0:41 10096 100 17,2.014472,84.624791,84.648335,33502,33584,1049895,1049895,82.633863,3,...,84.691622675,33792,33874,1049895,1049895,82.677151,3,0,0.043288,0.052385
3,11:0:11 11:0:41 10093 100 17,2.013636,84.337275,84.387197,32829,32911,1049740,1049740,82.373561,3,...,84.42441131,33115,33197,1049740,1049740,82.410775,3,0,0.037215,0.045178
4,11:0:11 11:0:41 10092 100 17,2.013325,83.174090,83.281219,31208,31289,1050000,1050000,81.267895,3,...,83.487896235,31650,31731,1050000,1050000,81.474572,3,0,0.206677,0.254315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,11:0:101 11:0:41 10055 100 17,2.023600,83.662785,83.719689,31708,31789,1049744,1049744,81.696089,3,...,83.99175687,32307,32388,1049744,1049744,81.968157,3,0,0.272068,0.333024
896,11:0:101 11:0:41 10006 100 17,2.020246,6.002052,6.146634,149,153,8230,8230,4.126388,1,...,5.34522497,150,152,8230,8230,3.324979,1,0,-0.801409,-19.421557
897,11:0:101 11:0:41 10025 100 17,2.021298,6.627625,6.768255,173,177,8232,8232,4.746957,1,...,6.006504556,176,179,8232,8232,3.985207,1,0,-0.761751,-16.047134
898,11:0:101 11:0:41 10057 100 17,2.023933,83.935175,83.987189,32175,32256,1049599,1049599,81.963256,3,...,84.247605378,32774,32856,1049599,1049599,82.223673,3,0,0.260417,0.317724
899,11:0:101 11:0:41 10058 100 17,2.024244,84.904460,84.919760,34465,34547,1049978,1049978,82.895516,3,...,84.989595242,34904,34985,1049978,1049978,82.965351,3,0,0.069836,0.084245

In [4]:
# Group by origin priority group and calculate the required statistics
group_stats = merged_df.groupby('origin_pg:_no_sp').agg(
    FCT_Total_No_SP=pd.NamedAgg(column='FCT:_no_sp', aggfunc='sum'),
    FCT_Total_SP=pd.NamedAgg(column='FCT:_sp', aggfunc='sum'),
    Total_FCT_Change=pd.NamedAgg(column='FCT Change', aggfunc='sum'),
    Mean_FCT_Change=pd.NamedAgg(column='FCT Change', aggfunc='mean'),
    Mean_FCT_Per_Change=pd.NamedAgg(column=''FCT % Change', aggfunc='mean'),
    Count_FCT_Decrease=pd.NamedAgg(column='FCT Change', aggfunc=lambda x: (x <= 0.0).sum()),
    Total_Flows=pd.NamedAgg(column='FCT Change', aggfunc='size')
)

# Calculate percentage of flows with decreased FCT
group_stats['Percentage_FCT_Decrease'] = (group_stats['Count_FCT_Decrease'] / group_stats['Total_Flows']) * 100

# Display the summarized statistics
group_stats.reset_index()

,origin_pg:_no_sp,FCT_Total_No_SP,FCT_Total_SP,Total_FCT_Change,Mean_FCT_Change,Mean_FCT_Per_Change,Count_FCT_Decrease,Total_Flows,Percentage_FCT_Decrease
0,1,2330.727962,1642.868600,-687.859362,-24.925116,-1.698418,370,405,91.358025
1,2,2218.841343,2143.111509,-75.729834,1.279787,-0.841443,31,90,34.444444
2,3,32290.776029,32178.131560,-112.644468,-0.266236,-0.278134,133,405,32.839506

In [5]:
merged_df.to_csv("./result_4_multiCast.csv")

In [6]:
#0 	1 	15470.217402 	15470.217336 	-0.000066 	-4.888741e-07 	1 	135 	0.740741

In [7]:
# in 40Mpbs some high pg flows' fct has increase as follow: 
    # 131,11:0:21 11:0:41 10020 100 17,2.00055418,125.34508296,125.364080097,2083,2086,123.363525917,1,0,2.00055418,125.366682448,125.366845447,2086,2086,123.366291267,1,0,0.0027653499999900077,0.002241626914790485
        # use high_60 replace high_61
    # 156,11:0:21 11:0:41 10004 100 17,2.000111196,113.565199616,113.58213076,1627,1629,111.582019564,1,0,2.000111196,113.610388046,113.610699046,1629,1629,111.61058785,1,0,0.02856828599999517,0.02560294760000224
        # use high_12 replace high_13
    # 183,11:0:21 11:0:41 10040 100 17,2.001132561,120.484628618,120.506937341,1108,1111,118.50580478,1,0,2.001132561,120.556739024,120.557038222,1113,1114,118.555905661,1,0,0.05010088099999166,0.04227715350568809
        # use high_120 replace high_121
    # 180,11:0:21 11:0:41 10029 100 17,2.000844572,121.428252899,121.447419428,1951,1951,119.446574856,1,0,2.000844572,121.44740644,121.447481839,1951,1951,119.446637267,1,0,6.241100000181632e-05,5.225013783530965e-05
        # use high_87 replace high_88   
    # 256,11:0:31 11:0:41 10022 100 17,2.000626577,123.632155519,123.651544052,2069,2082,121.650917475,1,0,2.000626577,123.653212468,123.653460069,2069,2069,121.652833492,1,0,0.001916016999999215,0.0015750123712737045
        # use high_67 replace high_68       
    # 50,11:0:11 11:0:41 10020 100 17,2.00054058,124.004466398,124.021815529,2071,2075,122.021274949,1,0,2.00054058,124.023811895,124.023887895,2071,2071,122.023347315,1,0,0.0020723659999930533,0.0016983644867333333
        # use high_59 replace high_60
        # use high_60 replace high_61